import Navbar from "@/Components/Header/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Quicksand } from "next/font/google";

const font = Quicksand({ subsets: ["latin"], weight: "600" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
